### ISSUE TITLE
Summary of Corrected Tracks

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/neurolincsdreamchallenge#16]
These files were provided as corrections to the original curated cell file [syn11378063](https://www.synapse.org/#!Synapse:syn17087846):

**Corrected File**|**In Response To**
:-----:|:-----:
[syn17087846](https://www.synapse.org/#!Synapse:syn17087846)|#5
[syn17096732](https://www.synapse.org/#!Synapse:syn17096732)|#5
[syn17933845](https://www.synapse.org/#!Synapse:syn17933845)|#5
[syn18134075](https://www.synapse.org/#!Synapse:syn18134075)|#7
[syn18160422](https://www.synapse.org/#!Synapse:syn18160422)|#8
[syn18174013](https://www.synapse.org/#!Synapse:syn18174013)|#9

Replacing the records in the original curated cell file by index (Experiment, Well, ObjectTrackID, TimePoint) results in some erroneous tracks as demonstrated [here](https://github.com/Sage-Bionetworks/neurolincsdreamchallenge/issues/5#issuecomment-574440129).

To resolve this issue, we will instead replace at the track level (Experiment, Well, ObjectTrackID).

**Comment by jlinsley1983** [comment]
I checked the example issue you mentioned above that we discussed yesterday in the teleconference and it is as I suspected. Please replace the entire track that Jaslin gave you rather than the instances.
