### ISSUE TITLE
Uneven tracks

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/neurolincsdreamchallenge#18]
These tracks have a Live_Cells value but no Lost_Tracking value at some TimePoint.

```
# A tibble: 14 x 7
   Experiment   Well  ObjectTrackID ObjectLabelsFound TimePoint Live_Cells Lost_Tracking
   <chr>        <chr>         <int>             <int>     <int> <lgl>      <lgl>        
 1 LINCS062016B B8               20                20         1 FALSE      FALSE        
 2 LINCS062016B B8               20                20        12 FALSE      FALSE        
 3 LINCS062016B B8               20                20        13 FALSE      NA           
 4 LINCS062016B C7               30                30         1 TRUE       FALSE        
 5 LINCS062016B C7               30                30         2 TRUE       FALSE        
 6 LINCS062016B C7               30                30         3 TRUE       FALSE        
 7 LINCS062016B C7               30                30         4 TRUE       FALSE        
 8 LINCS062016B C7               30               112         5 TRUE       FALSE        
 9 LINCS062016B C7               30               112         6 TRUE       FALSE        
10 LINCS062016B C7               30               112         7 TRUE       FALSE        
11 LINCS062016B C7               30               112         8 TRUE       FALSE        
12 LINCS062016B C7               30               112         9 TRUE       FALSE        
13 LINCS062016B C7               30               112        10 TRUE       NA           
14 LINCS062016B D6               40                40         1 FALSE      NA       
```

I'm not sure if Lost_Tracking is relevant in most of these cases, but these are the only tracks that have an uneven number of measurements for Live_Cells and Lost_Tracking so it seems worth it to figure out what went wrong here.

**Comment by jlinsley1983** [comment]
If the Live_Cells=FALSE, it is dead and should be ignored whether or not there is a lost_tracking value. The example below where Live_Cells=TRUE, I checked the specific example. It appears the curation is wrong and the T10 timepoint should be removed (the cell actually dies at T9). Not sure how it ended up that way.

Best,
Jeremy

**Comment by philerooski** [comment]
I've created a file that will replace the rows that have missing Lost_Tracking values: https://www.synapse.org/#!Synapse:syn21568415

As Jeremy said, sometimes the value doesn't matter because Live_Cells=FALSE but it will be good to have Live_Cells/Lost_Tracking values for all rows.
