### ISSUE TITLE
Tracks that are missing a TimePoint = 0 row

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/neurolincsdreamchallenge#19]
These two tracks have slightly different issues. The LINCS062016B track has NA values for both Live_Cells and Lost_Tracking for its first TimePoint (LINCS062016B starts at TimePoint 1 in the source file). The AB-SOD1-KW4-WTC11-Survival only has a row for TimePoint = 3, no other TimePoints are present.

```
# A tibble: 4 x 7
  Experiment                 Well  ObjectTrackID ObjectLabelsFound TimePoint Live_Cells Lost_Tracking
  <chr>                      <chr>         <int>             <int>     <int> <lgl>      <lgl>        
1 LINCS062016B               A6               12                12         1 NA         NA           
2 LINCS062016B               A6               12                12         2 TRUE       FALSE        
3 LINCS062016B               A6               12                11         3 TRUE       TRUE         
4 AB-SOD1-KW4-WTC11-Survival B1                6                 6         3 NA         NA                  
```

We can drop these tracks or if we would like to provide the missing rows I can include these tracks in the final dataset.

**Comment by jlinsley1983** [comment]
Hi Phil,

Delete the #4 track form the data set (AB-SOD1-KW4-WTC11-Survival, B1, #6).

For LINCS062016B the NA’s in timepoint 1 are an error. Both Live_Cells and Lost_tracking need to be TRUE, not NA.

Best,
Jeremy

**Comment by philerooski** [comment]
Corrected rows here: https://www.synapse.org/#!Synapse:syn21574264
