### ISSUE TITLE
adjust data to account for all time points and appropriate labeling of Lost_Tracking

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/neurolincsdreamchallenge#3]
Current data (https://www.synapse.org/#!Synapse:syn11378063/tables/) has missing time points per Experiment + Well + Object. The `Lost_Tracking` column is inappropriately used to indicate that the *next* timepoint (and subsequent ones until a manually curated track comes back) is lost.

We need to transform this to:

1. Fill in missing time points. This table (https://www.synapse.org/#!Synapse:syn11817859/tables/) has the start and end time point for each experiment that can be used to determine how many time points there should be for each object.
2. Change the `Lost_Tracking` where it's `True` to `False`, and the missing time points get `Lost_Tracking` = `True`.

Task:

Make a new table with these changes in R - do not modify existing table.

**Comment by philerooski** [comment]
I was working on a script to fix but the logic is incomplete https://github.com/philerooski/neurolincsdreamchallenge/blob/fix-lost-tracking/R/fix_lost_tracking.R

Maybe it's time to make this issue a priority again.

**Comment by jaslinkalra** [comment]
Okay, I suggest we update the manual errors I provided as csv file first as I found lost tracking cases similar to this issue here stemming from manual errors in reporting correct object labels found. Let me know if I need to update the curation table in synapse.

**Comment by philerooski** [comment]
Note to self (correct me if I'm wrong): Update the relevant rows in this

https://www.synapse.org/#!Synapse:syn11378063/tables/

with this

https://www.synapse.org/#!Synapse:syn18134075

before fixing Lost_Tracking labels as described above.

**Comment by philerooski** [comment]
Fixed by #17
