### ISSUE TITLE
Unexplained gaps

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/neurolincsdreamchallenge#6]
In many cases, Lost_Tracking is never marked as true, yet there is a a gap in the the records for a given Experiment/Well/ObjectTrackID combo.

I'm defining a "gap" as an Experiment/Well/ObjectTrackID combo where there are true or false values in the Live_Cells/Lost_Tracking columns, then a row or more of NA values (missing row in the original data), then (later on) at least one or more true or false entry for Live_Cells/Lost_Tracking. The "unexplained" part comes from the lack of a true value for any Lost_Tracking values. 

An example:

```
> curated_cell_data_full %>% 
+     filter(Experiment == "KS-AB-iMN-TDP43-Survival", Well == "A4", ObjectTrackID == 55) %>%
+     select(Experiment, Well, ObjectTrackID, TimePoint, Live_Cells, Lost_Tracking)
# A tibble: 19 x 6
# Groups:   Experiment, Well, ObjectTrackID [1]
   Experiment               Well  ObjectTrackID TimePoint Live_Cells Lost_Tracking
   <chr>                    <chr>         <int>     <int> <lgl>      <lgl>        
 1 KS-AB-iMN-TDP43-Survival A4               55         0 TRUE       FALSE        
 2 KS-AB-iMN-TDP43-Survival A4               55         1 TRUE       FALSE        
 3 KS-AB-iMN-TDP43-Survival A4               55         2 NA         NA           
 4 KS-AB-iMN-TDP43-Survival A4               55         3 TRUE       FALSE        
 5 KS-AB-iMN-TDP43-Survival A4               55         4 NA         NA           
 6 KS-AB-iMN-TDP43-Survival A4               55         5 NA         NA         
# ... with 13 more rows
```
In the original dataset, this looks like:
```
> curated_cell_data %>% filter(Experiment == "KS-AB-iMN-TDP43-Survival", Well == "A4", ObjectTrackID == 55)
# A tibble: 3 x 6
  Experiment               ObjectTrackID Well  TimePoint Live_Cells Lost_Tracking
  <chr>                            <int> <chr>     <int> <chr>      <chr>        
1 KS-AB-iMN-TDP43-Survival            55 A4            0 true       false        
2 KS-AB-iMN-TDP43-Survival            55 A4            1 true       false        
3 KS-AB-iMN-TDP43-Survival            55 A4            3 true       false   
```

I've uploaded a gist which lists all the unexplained gaps https://gist.github.com/philerooski/a7802f10cf4b381d9398930ff3b9e332

**Comment by philerooski** [comment]
@jaslinkalra Could you explain what the `Timepoint` column in the survival files represents? I'm seeing a relationship between the value in this column with these gaps in the cell data. For example, referencing the survival file for AB-CS47iTDP-Survival, this cell has value 9 in the `Timepoint` column and I also see a gap at timepoint 9 in the curated cell data.

```
             Experiment Well ObjectTrackID TimePoint Live_Cells Lost_Tracking
1  AB-CS47iTDP-Survival   C8            21         0       TRUE         FALSE
2  AB-CS47iTDP-Survival   C8            21         1       TRUE         FALSE
3  AB-CS47iTDP-Survival   C8            21         2       TRUE         FALSE
4  AB-CS47iTDP-Survival   C8            21         3       TRUE         FALSE
5  AB-CS47iTDP-Survival   C8            21         4       TRUE         FALSE
6  AB-CS47iTDP-Survival   C8            21         5       TRUE         FALSE
7  AB-CS47iTDP-Survival   C8            21         6       TRUE         FALSE
8  AB-CS47iTDP-Survival   C8            21         7       TRUE         FALSE
9  AB-CS47iTDP-Survival   C8            21         8       TRUE         FALSE
10 AB-CS47iTDP-Survival   C8            21         9         NA            NA
11 AB-CS47iTDP-Survival   C8            21        10       TRUE         FALSE
12 AB-CS47iTDP-Survival   C8            21        11       TRUE         FALSE
13 AB-CS47iTDP-Survival   C8            21        12       TRUE         FALSE
14 AB-CS47iTDP-Survival   C8            21        13       TRUE         FALSE
15 AB-CS47iTDP-Survival   C8            21        14       TRUE         FALSE
16 AB-CS47iTDP-Survival   C8            21        15       TRUE         FALSE
```

**Comment by jaslinkalra** [comment]
Timepoints are points of time a cell/Object was last seen live when curating. For some reason, my script did not fill in for timepoint 9 here, but I have attached the correct curation.

[unexplainedgaps.txt](https://github.com/Sage-Bionetworks/neurolincsdreamchallenge/files/2849480/unexplainedgaps.txt)
![unexplained gaps](https://user-images.githubusercontent.com/11657113/52540655-c3581f80-2d40-11e9-9069-53f578cfa602.PNG)

**Comment by philerooski** [comment]
I'm seeing 212 of these gaps in recording where we have:

1. null values for both Lost_Tracking and Live_Cells at the current TimePoint.
2. non-null values for Lost_Tracking and Live_Cells at the previous TimePoint.
3. The cell was seen alive (Live_Cells = TRUE) at a later TimePoint.

I'm trying to determine if there is a systematic way to fill in these gaps, considering the amount of work it would take to correct manually.

Here's where those gaps occur for reference (This is more up to date than the gist linked to above): [cell_record_gaps.txt](https://github.com/Sage-Bionetworks/neurolincsdreamchallenge/files/2852788/cell_record_gaps.txt)

**Comment by jaslinkalra** [comment]
Wow that's a lot. I had no idea there are many of these. Best way is to look at corresponding ObjectLabelsFound in survival files here I think. https://www.synapse.org/#!Synapse:syn17079347
Perhaps the ObjectLabelsFound per timepoint can fill those gaps???

**Comment by jaslinkalra** [comment]
I take that back. From this one example you presented, I see that at Timepoint 9 the manual curation was wrongfully added into survival file. It's not 132 at T10 but actually 21 from looking at the cell masks and image overlays. This information is preserved in encoded cell masks that are present in synapse.

We can try to solve this in parallel perhaps. I would need same information you provided in the example for all these entries and I can manually correct them because this itself is a manual problem. 

Another approach was to look at encoded masks here https://www.synapse.org/#!Synapse:syn8067743
to fill the gaps

**Comment by philerooski** [comment]
Here is the cell record gaps file but with the missing TimePoint indicated: 
[cell_record_gaps.txt](https://github.com/Sage-Bionetworks/neurolincsdreamchallenge/files/2866174/cell_record_gaps.txt)

**Comment by philerooski** [comment]
Beginning at the "gap" we will set Lost_Tracking = TRUE for the rest of the TimePoints as per @jlinsley1983 suggestion in the March 6 email thread.
