### ISSUE TITLE
Identify erroneous object labels.

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/neurolincsdreamchallenge#7]
From #6

We spot-checked one example from `KS-AB-iMN-TDP43-Survival` (Well A3, ObjectTrackID = 6). This has a typo for time T1 (reads 922 instead of 92).

@philerooski, can you scan all of the survival files here (https://www.synapse.org/#!Synapse:syn17079347) to check if the values in columns 'T0' through Tx match something that is in column `ObjectLabelsFound`? This should identify any human errors when entering a object label.

_Originally posted by @kdaily in https://github.com/Sage-Bionetworks/neurolincsdreamchallenge/issues/6#issuecomment-451303336_

**Comment by jaslinkalra** [comment]
Is this still an issue after the Dream Challenge talk?

Can we identify some and I look at image files over time for what happened?

**Comment by kdaily** [comment]
@jaslinkalra I sent an email. Reposting here as well so @philerooski knows what's up.

I did the comparison of the object labels taken directly from the image masks at each time point in each well for each experiment. I found every instance of a record in Jaslin's survival file that didn't match an object in a well at any time point in the image mask. 

I did four experiments, and something is amiss with one. Here's the count of potential errors:

```
  Experiment                   n
  <chr>                    <int>
1 AB-CS47iTDP-Survival      1681
2 KS-AB-iMN-TDP43-Survival     2
3 LINCS062016A                 1
4 LINCS092016B                 2
```

Here's the list I come up with:

https://www.synapse.org/#!Synapse:syn17937743

**Comment by kdaily** [comment]
Code for processing this is here:

https://github.com/Sage-Bionetworks/neurolincsscoring/blob/master/exec/survival-file-manual-errors.R

**Comment by jaslinkalra** [comment]
I have updated censored wells so the errors should be reduced specifically for AB-CS47iTDP-Survival as there were wells that did not get manually curated and the information is not available for curation as well as there is no encoded masks.
https://www.synapse.org/#!Synapse:syn11709601/tables/

For the rest of them, how can I know what part is wrong? what information should I provide you guys with?The csv files phil shared last time with double information helped a ton to assess what value was falsely curated for a particular well.

For now, I can check for the three datasets and provide you with information for object tracks, live cells, lost tracking and others.

**Comment by jaslinkalra** [comment]
The correct curation is attached here- https://www.synapse.org/#!Synapse:syn17937743

**Comment by kdaily** [comment]
@jaslinkalra I think you meant https://www.synapse.org/#!Synapse:syn18134075!

Thank you for providing.

**Comment by jaslinkalra** [comment]
Yes you are correct. Sorry about the wrong link.

**Comment by kdaily** [comment]
Marking resolved, though this file needs to be integrated into the curated table. Will open separate issue.
