### ISSUE TITLE
Zombie cells

### ISSUE THREAD

**Issue by philerooski** [Sage-Bionetworks/neurolincsdreamchallenge#8]
These cells die then come back to life at a later timepoint.

```
  Experiment               ObjectTrackID Well 
  <chr>                            <int> <chr>
1 KS-AB-iMN-TDP43-Survival            45 C5   
2 KS-AB-iMN-TDP43-Survival            10 F5   
3 LINCS062016A                        33 D4   
4 LINCS062016B                        52 A3   
5 LINCS062016B                        31 B8  
```

For example:
```
                 Experiment Well ObjectTrackID TimePoint Live_Cells Lost_Tracking
1  KS-AB-iMN-TDP43-Survival   C5            45         0      FALSE         FALSE
2  KS-AB-iMN-TDP43-Survival   C5            45         1         NA            NA
3  KS-AB-iMN-TDP43-Survival   C5            45         2         NA            NA
4  KS-AB-iMN-TDP43-Survival   C5            45         3         NA            NA
5  KS-AB-iMN-TDP43-Survival   C5            45         4         NA            NA
6  KS-AB-iMN-TDP43-Survival   C5            45         5         NA            NA
7  KS-AB-iMN-TDP43-Survival   C5            45         6       TRUE         FALSE
```

**Comment by jaslinkalra** [comment]
These cells have been corrected for curation here- https://www.synapse.org/#!Synapse:syn18160422
Found few other objects that were curated incorrectly due to the curation errors that occurred for the identified objects. Basically, an ObjectLabelsFound was confused for a different number for example, 45 in C5 well above was halfway curated for ObjectLabelsFound 46.

**Comment by kdaily** [comment]
@phil did other things addressed (or our decision to replace entire tracks instead of specific rows) fix this issue?

**Comment by philerooski** [comment]
Yes. There are no more zombie tracks because that would violate the rule
> If Live_Cells is FALSE, all subsequent Live_Cells values must be FALSE.
